spring.application.name=my-portafolio-backend
spring.datasource.url=jdbc:postgresql://ep-small-frost-acejih61-pooler.sa-east-1.aws.neon.tech/porfolio?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_AGa6C7eLTKvY

# HikariCP (corrección: maximum, no "maximun")
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1800000



spring.sql.init.mode=always